1. SELECT MIN(WEIGHT) FROM ITEMS;
2. SELECT * FROM WAREHOUSES WHERE CITY="PUNE";
3. SELECT * FROM CUSTOMER INNER JOIN ORDERS ON CUSTOMER.CNO=ORDERS.CNO WHERE CUSTOMER.CNAME='Mr. Patil';
4. SELECT WID, COUNT(SID) FROM STORES GROUP BY WID
5. SELECT ITEMNO, COUNT(ONO) FROM ORDERS_ITEM GROUP BY ITEMNO LIMIT 1;
6. SELECT * FROM ORDERS WHERE CNO IN(SELECT CNO FROM CUSTOMER)